server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    jdbcUrl: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
    file-path:
      output: "outputs/users.csv"
  cache:
    type: redis
    redis:
      time-to-live: 600000
  redis:
    host: "redis-10405.c262.us-east-1-3.ec2.redns.redis-cloud.com"
    port: 10405
    username: "default"
    password: "*******"
hibernate:
  hbm2ddl:
    auto: update
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600 # in seconds
  refreshable-duration: 7200 # in seconds
default-admin-password: ${ADMIN_PASSWORD}