spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678x@X
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
tenant1:
  datasource:
    url: jdbc:mysql://localhost:3306/tenant1_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678x@X
tenant2:
  datasource:
    url: jdbc:mysql://localhost:3306/tenant2_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678x@X
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in seconds
  refreshable-duration: 7200 # in seconds
tenants: default, tenant1, tenant2

